### ISSUE TITLE
Fails to run when there is "No current active profile"

### ISSUE THREAD

**Issue by prasadjlv** [giovtorres/ansible-role-tuned#1]
When all tunings are switched off (tuned-adm off) that results in:
[root@localhost] tuned-adm active
No current active profile.

This role fails to execute as shown below:

TASK [ansible-role-tuned : Get tuned profile.] ************************************************************************************************************************************************
task path: /etc/ansible/roles/ansible-role-tuned/tasks/main.yml:13
**fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/sbin/tuned-adm", "active"], "delta": "0:00:00.140199", "end": "2018-03-15 23:21:45.311486", "msg": "non-zero return code", "rc": 1, "start": "2018-03-15 23:21:45.171287", "stderr": "", "stderr_lines": [], "stdout": "No current active profile.", "stdout_lines": ["No current active profile."]}**

I believe it needs a simple ignore_errors: yes in tasks/main.yml. I will submit a PR, can you please review and approve it.

Thank you.

**Comment by giovtorres** [comment]
Are you still getting this error?

**Comment by prasadjlv** [comment]
No, the issue is fixed. I am closing this issue.
